name: ai_pt
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  flutter_dotenv: ^5.2.1
  flutter_scrolling_fab_animated: ^0.1.5
  http: ^1.3.0
  path: ^1.9.0
  sqflite: ^2.2.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.1.0
  flutter_background_service: ^5.1.0
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.40
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
